# bind9-config
# Autogenerated from man page /usr/share/man/man1/bind9-config.1.gz
complete -c bind9-config -l cflags --description 'Prints the compiler command line options required to compile files that use I…'
complete -c bind9-config -l exec-prefix --description 'Prints the directory prefix used in the ISC BIND installation for architectur…'
complete -c bind9-config -l libs --description 'Prints the linker command line options used to link with the ISC BIND librari…'
complete -c bind9-config -l prefix --description 'Prints the directory prefix used in the ISC BIND installation for architectur…'
complete -c bind9-config -l version --description 'Prints the version of the installed ISC BIND suite.'

