# i3lock
# Autogenerated from man page /usr/share/man/man1/i3lock.1.gz
complete -c i3lock -s v -l version --description 'Display the version of your  i3lock.'
complete -c i3lock -s n -l nofork --description 'Don\'t fork after starting.'
complete -c i3lock -s b -l beep --description 'Enable beeping.'
complete -c i3lock -s c -l config --description 'Load configuration file.'

