// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1582299600);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1582306865);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1582295344);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1582295464);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1582295584);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1582205995);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1582306985);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 33429);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1582205244);
user_pref("browser.laterrun.bookkeeping.sessionCount", 11);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e29d92c4-73da-4c9e-9457-ac4803beb4f2}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1582306863818");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1582308638818");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1582306864877");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1582310464877");
user_pref("browser.search.region", "BR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200206211857");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1597415623");
user_pref("browser.slowStartup.averageTime", 6237);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200206211857");
user_pref("browser.startup.homepage_override.mstone", "68.5.0");
user_pref("browser.startup.lastColdStartupCheck", 1597415621);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1582205252140");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "68.5.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 21 Feb 2020 16:10:51 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1582299601);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200206211857");
user_pref("extensions.lastAppVersion", "68.5.0");
user_pref("extensions.lastPlatformVersion", "68.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"f365343b-f56d-4ea8-96f3-adb1cd3ff4d6\",\"fxmonitor@mozilla.org\":\"e54b8c04-4141-45f2-a9a1-9547e942590a\",\"screenshots@mozilla.org\":\"26ac276b-bc64-4055-97c6-4c5349176067\",\"webcompat-reporter@mozilla.org\":\"84d1f638-c54b-4a5a-a1e0-04e878f97628\",\"webcompat@mozilla.org\":\"3b0315b3-dc44-42e6-a3ee-64602e956579\",\"default-theme@mozilla.org\":\"40cdc082-1a62-4ccd-959f-4243b1473a84\",\"google@search.mozilla.org\":\"924dfc0f-4a66-44e6-b2bc-5b6c556139ed\",\"amazondotcom@search.mozilla.org\":\"2f03f29c-acf4-441e-8016-c0fc2eab7d6a\",\"bing@search.mozilla.org\":\"d93882f2-b8fa-4675-9dd8-472b955625ca\",\"ddg@search.mozilla.org\":\"2db8c99b-7204-4570-be2a-d2b5c315a3e2\",\"ebay@search.mozilla.org\":\"3e34738b-2af8-4deb-9f06-51479972b0b5\",\"twitter@search.mozilla.org\":\"29cf9f27-6182-4d0e-9703-5b1bb53c8e8e\",\"wikipedia@search.mozilla.org\":\"7d27f1fd-1580-48de-a70e-8e1f9eec6e55\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1582205498);
user_pref("media.gmp-manager.buildID", "20200206211857");
user_pref("media.gmp-manager.lastCheck", 1582295345);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1582205498);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "8cf6cfa5-3703-45a8-ae1e-8b288156d943");
user_pref("security.sandbox.plugin.tempDirSuffix", "8437b810-7262-404a-9f28-4903dd8e6217");
user_pref("services.blocklist.pinning.checked", 1582295583);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1582243284934\"");
user_pref("services.settings.last_update_seconds", 1582295583);
user_pref("services.settings.main.cfr-fxa.last_check", 1582295583);
user_pref("services.settings.main.cfr.last_check", 1582295583);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1582295583);
user_pref("services.settings.main.hijack-blocklists.last_check", 1582295583);
user_pref("services.settings.main.language-dictionaries.last_check", 1582295583);
user_pref("services.settings.main.sites-classification.last_check", 1582295583);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1582295583);
user_pref("services.settings.security.onecrl.checked", 1582295583);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1582205498);
user_pref("toolkit.startup.last_success", 1597415615);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20200206211857");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
